-- ============================================================================
-- Demo data — run AFTER schema.sql, once, in the Supabase SQL Editor.
-- Passwords below are bcrypt hashes of the plaintext shown in each comment.
-- All demo passwords follow the pattern "<Role>@123" — CHANGE IN PRODUCTION.
-- ============================================================================

-- Plaintext passwords behind the hashes used below:
--   SuperAdmin@123  -> super admin
--   Admin@123       -> gym admins
--   Staff@123       -> all staff
--   Member@123      -> all members
-- Hashes are bcrypt (10 rounds), generated by backend/scripts/hash-passwords.mjs.

do $$
declare
  v_superadmin_hash text := '$2a$10$9xNHflgRsF7Qw3CG/cERZeSm769/MkKeHVN7XJyPtY4r464PdDvtC';
  v_admin_hash      text := '$2a$10$Zdvv3KJ7kZLJnv5AmsO5F.69QPJvLelQn8dazn78KfX3AIvfeBR.q';
  v_staff_hash      text := '$2a$10$qvefmOCjfXzp34bwjhn.q.wo47pYW5kAQxPoxilvqXhB3Z9yJE6WO';
  v_member_hash     text := '$2a$10$JtG4P9kg.n9IPkKsFLBysejzzml1bXUdlfqdoU9vtsjvZ.q7ee9mi';

  gym_a uuid;
  gym_b uuid;
  admin_a uuid;
  admin_b uuid;
  staff_a1 uuid;
  staff_a2 uuid;
  staff_b1 uuid;
  plan_a_monthly uuid;
  plan_a_yearly uuid;
  plan_b_monthly uuid;
  m_a1 uuid; m_a2 uuid; m_a3 uuid; m_a4 uuid;
  m_b1 uuid; m_b2 uuid; m_b3 uuid;
  sub_id uuid;
begin
  -- Super Admin (no gym)
  insert into users (id, gym_id, role, full_name, email, password_hash, status)
  values (gen_random_uuid(), null, 'super_admin', 'Platform Owner', 'superadmin@gymsaas.demo', v_superadmin_hash, 'active');

  -- Gym A
  insert into gyms (id, name, address, phone, email, status, subscription_status)
  values (gen_random_uuid(), 'Iron Peak Fitness', '12 Wadajir Road, Mogadishu', '+252611000001', 'contact@ironpeak.demo', 'active', 'active')
  returning id into gym_a;

  insert into users (id, gym_id, role, full_name, email, password_hash, status)
  values (gen_random_uuid(), gym_a, 'gym_admin', 'Amina Yusuf', 'admin@ironpeak.demo', v_admin_hash, 'active')
  returning id into admin_a;

  insert into users (id, gym_id, role, full_name, email, password_hash, title, permissions, status)
  values (gen_random_uuid(), gym_a, 'staff', 'Ahmed Ali', 'ahmed@ironpeak.demo', v_staff_hash, 'Receptionist', '{"members":true,"attendance":true}'::jsonb, 'active')
  returning id into staff_a1;

  insert into users (id, gym_id, role, full_name, email, password_hash, title, permissions, status)
  values (gen_random_uuid(), gym_a, 'staff', 'Ayaan Osman', 'ayaan@ironpeak.demo', v_staff_hash, 'Cashier', '{"payments":true}'::jsonb, 'active')
  returning id into staff_a2;

  insert into membership_plans (id, gym_id, name, duration_days, price, status)
  values (gen_random_uuid(), gym_a, 'Monthly', 30, 25.00, 'active') returning id into plan_a_monthly;
  insert into membership_plans (id, gym_id, name, duration_days, price, status)
  values (gen_random_uuid(), gym_a, 'Yearly', 365, 240.00, 'active') returning id into plan_a_yearly;

  insert into members (id, gym_id, member_code, full_name, phone, gender, join_date, membership_plan_id, start_date, expiry_date, status, password_hash)
  values (gen_random_uuid(), gym_a, 'M001', 'Farah Hassan', '+252611100001', 'male', current_date - 60, plan_a_monthly, current_date - 10, current_date + 20, 'active', v_member_hash)
  returning id into m_a1;
  insert into members (id, gym_id, member_code, full_name, phone, gender, join_date, membership_plan_id, start_date, expiry_date, status, password_hash)
  values (gen_random_uuid(), gym_a, 'M002', 'Sagal Warsame', '+252611100002', 'female', current_date - 40, plan_a_yearly, current_date - 40, current_date + 325, 'active', v_member_hash)
  returning id into m_a2;
  insert into members (id, gym_id, member_code, full_name, phone, gender, join_date, membership_plan_id, start_date, expiry_date, status, password_hash)
  values (gen_random_uuid(), gym_a, 'M003', 'Khalid Nur', '+252611100003', 'male', current_date - 100, plan_a_monthly, current_date - 35, current_date - 5, 'expired', v_member_hash)
  returning id into m_a3;
  insert into members (id, gym_id, member_code, full_name, phone, gender, join_date, membership_plan_id, start_date, expiry_date, status, password_hash)
  values (gen_random_uuid(), gym_a, 'M004', 'Hodan Abdi', '+252611100004', 'female', current_date - 5, plan_a_monthly, current_date - 5, current_date + 25, 'active', v_member_hash)
  returning id into m_a4;

  insert into subscriptions (id, gym_id, member_id, plan_id, start_date, end_date, status)
  values (gen_random_uuid(), gym_a, m_a1, plan_a_monthly, current_date - 10, current_date + 20, 'active') returning id into sub_id;
  insert into payments (gym_id, member_id, subscription_id, amount, payment_date, method, received_by, notes)
  values (gym_a, m_a1, sub_id, 25.00, current_date - 10, 'cash', staff_a2, 'Monthly renewal');

  insert into subscriptions (id, gym_id, member_id, plan_id, start_date, end_date, status)
  values (gen_random_uuid(), gym_a, m_a2, plan_a_yearly, current_date - 40, current_date + 325, 'active') returning id into sub_id;
  insert into payments (gym_id, member_id, subscription_id, amount, payment_date, method, received_by, notes)
  values (gym_a, m_a2, sub_id, 240.00, current_date - 40, 'zaad', staff_a2, 'Yearly plan');

  insert into subscriptions (id, gym_id, member_id, plan_id, start_date, end_date, status)
  values (gen_random_uuid(), gym_a, m_a3, plan_a_monthly, current_date - 35, current_date - 5, 'expired');

  insert into subscriptions (id, gym_id, member_id, plan_id, start_date, end_date, status)
  values (gen_random_uuid(), gym_a, m_a4, plan_a_monthly, current_date - 5, current_date + 25, 'active') returning id into sub_id;
  insert into payments (gym_id, member_id, subscription_id, amount, payment_date, method, received_by, notes)
  values (gym_a, m_a4, sub_id, 25.00, current_date - 5, 'edahab', staff_a2, 'New member sign-up');

  insert into attendance (gym_id, member_id, check_in_date, check_in_time, recorded_by) values
    (gym_a, m_a1, current_date, '08:15', staff_a1),
    (gym_a, m_a2, current_date, '09:00', staff_a1),
    (gym_a, m_a1, current_date - 1, '08:05', staff_a1),
    (gym_a, m_a4, current_date - 1, '17:30', staff_a1);

  insert into announcements (gym_id, title, message, status, created_by) values
    (gym_a, 'Gym closed Friday', 'Iron Peak Fitness will be closed this Friday for maintenance.', 'published', admin_a),
    (gym_a, 'New opening hours', 'Starting next week we open at 6 AM instead of 7 AM.', 'published', admin_a);

  insert into activity_logs (gym_id, user_id, action, related_table, related_id) values
    (gym_a, staff_a1, 'Checked in Farah Hassan (M001)', 'attendance', m_a1),
    (gym_a, staff_a2, 'Received $25.00 payment from Farah Hassan', 'payments', m_a1),
    (gym_a, admin_a, 'Created membership plan Yearly', 'membership_plans', plan_a_yearly);

  -- Gym B
  insert into gyms (id, name, address, phone, email, status, subscription_status)
  values (gen_random_uuid(), 'Coastal Strength Club', '5 Lido Beach Ave, Mogadishu', '+252611000002', 'contact@coastalstrength.demo', 'active', 'trial')
  returning id into gym_b;

  insert into users (id, gym_id, role, full_name, email, password_hash, status)
  values (gen_random_uuid(), gym_b, 'gym_admin', 'Mohamed Farah', 'admin@coastalstrength.demo', v_admin_hash, 'active')
  returning id into admin_b;

  insert into users (id, gym_id, role, full_name, email, password_hash, title, permissions, status)
  values (gen_random_uuid(), gym_b, 'staff', 'Ifrah Jama', 'ifrah@coastalstrength.demo', v_staff_hash, 'Manager', '{"reports":true,"members":true}'::jsonb, 'active')
  returning id into staff_b1;

  insert into membership_plans (id, gym_id, name, duration_days, price, status)
  values (gen_random_uuid(), gym_b, 'Monthly', 30, 20.00, 'active') returning id into plan_b_monthly;

  insert into members (id, gym_id, member_code, full_name, phone, gender, join_date, membership_plan_id, start_date, expiry_date, status, password_hash)
  values (gen_random_uuid(), gym_b, 'M001', 'Nasra Ali', '+252611200001', 'female', current_date - 20, plan_b_monthly, current_date - 20, current_date + 10, 'active', v_member_hash)
  returning id into m_b1;
  insert into members (id, gym_id, member_code, full_name, phone, gender, join_date, membership_plan_id, start_date, expiry_date, status, password_hash)
  values (gen_random_uuid(), gym_b, 'M002', 'Yusuf Omar', '+252611200002', 'male', current_date - 3, plan_b_monthly, current_date - 3, current_date + 27, 'active', v_member_hash)
  returning id into m_b2;
  insert into members (id, gym_id, member_code, full_name, phone, gender, join_date, membership_plan_id, start_date, expiry_date, status, password_hash)
  values (gen_random_uuid(), gym_b, 'M003', 'Zahra Said', '+252611200003', 'female', current_date - 50, plan_b_monthly, current_date - 20, current_date - 3, 'expired', v_member_hash)
  returning id into m_b3;

  insert into subscriptions (id, gym_id, member_id, plan_id, start_date, end_date, status)
  values (gen_random_uuid(), gym_b, m_b1, plan_b_monthly, current_date - 20, current_date + 10, 'active') returning id into sub_id;
  insert into payments (gym_id, member_id, subscription_id, amount, payment_date, method, received_by, notes)
  values (gym_b, m_b1, sub_id, 20.00, current_date - 20, 'cash', staff_b1, null);

  insert into subscriptions (id, gym_id, member_id, plan_id, start_date, end_date, status)
  values (gen_random_uuid(), gym_b, m_b2, plan_b_monthly, current_date - 3, current_date + 27, 'active') returning id into sub_id;
  insert into payments (gym_id, member_id, subscription_id, amount, payment_date, method, received_by, notes)
  values (gym_b, m_b2, sub_id, 20.00, current_date - 3, 'other', staff_b1, 'Bank transfer');

  insert into subscriptions (id, gym_id, member_id, plan_id, start_date, end_date, status)
  values (gen_random_uuid(), gym_b, m_b3, plan_b_monthly, current_date - 20, current_date - 3, 'expired');

  insert into attendance (gym_id, member_id, check_in_date, check_in_time, recorded_by) values
    (gym_b, m_b1, current_date, '07:45', staff_b1),
    (gym_b, m_b2, current_date - 1, '18:20', staff_b1);

  insert into announcements (gym_id, title, message, status, created_by) values
    (gym_b, 'Training schedule updated', 'New group training sessions start Monday at 6 PM.', 'published', admin_b);

  insert into activity_logs (gym_id, user_id, action, related_table, related_id) values
    (gym_b, staff_b1, 'Checked in Nasra Ali (M001)', 'attendance', m_b1),
    (gym_b, admin_b, 'Added member Yusuf Omar', 'members', m_b2);

end $$;
